// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trvvpvkflrbamgwlqhqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydnZwdmtmbHJiYW1nd2xxaHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTY3ODcsImV4cCI6MjA3MTg5Mjc4N30.mQ8kzlBPAz0YQPVYLpVrbhXiMiTnky6pAR4ArlNKswU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});